all: clean sound

sound: psg.o music.o effects.o
	cc68x -g psg.o music.o effects.o -o sound

psg.o: psg.c psg.h
	cc68x -g -c psg.c
	
music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

clean: 
	$(RM) *.o *.i sound
