# ************************************************************************ \
FILE:		MAKEFILE	\
AUTHORS:	James MacIsaac & Brad Ritten	\
PURPOSE:	Makefile for the project	\
				Removes erratic files	\
				Builds the objects	\
				Buidls the executable from  created objects	\
**************************************************************************	\


all: clean tetris

tetris: tetris.o raster.o rast_asm.o font.o model.o render.o events.o psg.o music.o effects.o
	cc68x -g tetris.o raster.o rast_asm.o font.o model.o render.o events.o psg.o music.o effects.o -o tetris

tetris.o: tetris.c tetris.h
	cc68x -g -c tetris.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	
font.o: font.c font.h
	cc68x -g -c font.c
	
model.o: model.c model.h
	cc68x -g -c model.c

render.o: render.c render.h
	cc68x -g -c render.c

events.o: events.c events.h
	cc68x -g -c events.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

clean: 
	$(RM) *.o *.i tetris
