all: clean tetris

tetris: tetris.o raster.o rast_asm.o font.o model.o render.o events.o
	cc68x -g tetris.o raster.o rast_asm.o font.o model.o render.o events.o -o tetris

tetris.o: tetris.c tetris.h
	cc68x -g -c tetris.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	
font.o: font.c font.h
	cc68x -g -c font.c
	
model.o: model.c model.h
	cc68x -g -c model.c

render.o: render.c render.h
	cc68x -g -c render.c
	
events.o: events.c events.h
	cc68x -g -c events.c

clean: 
	$(RM) *.o *.i tetris
