/*************************************************************************
FILE:
AUTHORS:	James MacIsaac & Brad Ritten
PURPOSE:
*************************************************************************/

#ifndef TYPES_H
#define TYPES_H

/*************************************************************************
TYPE DECLARATIONS
*************************************************************************/
typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

#endif
